import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");

  return (
    <html lang="en">
      <body
          className={inter.className}
          style={{
            background: theme?.value === 'light' ? '#fff' : '#000',
            color: theme?.value === 'light' ? '#000' : '#fff'
          }}
      >
        {children}
      </body>
    </html>
  );
}
